### ISSUE TITLE
'ORDER BY' in SELECT SQL query in FeedProcessor.java is not required

### ISSUE THREAD

**Issue by mohangandhiGH** [CUTR-at-USF/ontime-performance-calculator#1]
However, we are bringing all the records from database that falls between the service start and end range of GTFS static data, the order by in the select sql query is not required. 
Moreover, removing ORDER BY from query brings the results from server faster than with order by in query

**Comment by barbeau** [comment]
For now we can remove the `ORDER BY` query.  If in the future we want to add it back, to increase performance we could add an index to the timestamp field in the database table.
